### ISSUE TITLE
Add warning in case using Undeclared Variables

### ISSUE THREAD

**Issue by stamkov-sc** [OpusCapita/eslint-config#4]
This rule can help to locate potential ReferenceErrors resulting from misspellings of variable and parameter names. [See more about no-undef rule](http://eslint.org/docs/rules/no-undef)

**Comment by kvolkovich-sc** [comment]
Lot of eslint errors appears after these changes:     

`'require' is not defined`
`'module' is not defined`

To solve it you must make changes:

Add `env` property to global config: 

**.eslintrc**

```
{
  "extends": "eslint-config-opuscapita",
  "env": {
    "node": true
  }
}
```

Or you can add to specific file:

`/*eslint-env node*/`
